# Copyright 2021, Battelle Energy Alliance, LLC

stages:
    - linter
    - security
    - test

linter:
    stage: linter
    image:
        name: gcr.io/google-appengine/python
        entrypoint: [""]
    script:
        - echo "Run Linter"
        - python3 -m pip install yapf
        - chmod +x yapf.sh
        - bash yapf.sh
security:
    stage: security
    image:
        name: gcr.io/google-appengine/python
        entrypoint: [""]
    script:
        - echo "Run Security Check"
        - python3 -m pip install bandit
        - bandit -r adapter

test:
    stage: test
    image:
        name: gcr.io/google-appengine/python
        entrypoint: [""]
    script:
        - echo "Run unit tests"
        # - python3 -m pip install -r requirements.txt
        # - python3 -m pip install -r tests/requirements.txt
        # - coverage run -m pytest tests/ --cov=adapter --junit-xml=tests/reports/test-results.xml --cov-report html
